# Jekyll Development Dockerfile
FROM mcr.microsoft.com/devcontainers/ruby:3.1

# Install Jekyll dependencies
RUN gem install bundler

# Set the working directory
WORKDIR /workspace

# Expose the default Jekyll port
EXPOSE 4000